#!/bin/bash -e
# Copyright 2018 Pax Automa Systems, Inc.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#    http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This script runs periodically after first boot, pulls settings from Teamster
# and applies them, restarting any necessary services.

cursettings=${cursettings:-/etc/paxautoma/settings}
tmpsettings=${tmpsettings:-/tmp/operos-new-settings}
templatedir=/usr/share/operos

. /etc/systemd/scripts/_functions

has_var_changed() {
    local var=$1
    local old="$(load_settings ${tmpsettings}; eval echo \${$var})"
    local new="$(load_settings ${cursettings}; eval echo \${$var})"
    [ "$old" -eq "$new" ] || return 1
}

load_settings() {
    local src_file=$1
    set -a

    . ${src_file}
    CLUSTER_SN_MASK=$(netmask ${OPEROS_NODE_MASK//\/})
    CLUSTER_NODE_START=$(increment_ipv4 $OPEROS_CONTROLLER_IP 10)
    CLUSTER_SN_START=$(network $OPEROS_CONTROLLER_IP ${OPEROS_NODE_MASK//\/})
    CLUSTER_NODE_END=$(end_ip $CLUSTER_NODE_START ${OPEROS_NODE_MASK//\/})

    set +a
}

new_val() {
    local var=$1
    (
        load_settings ${cursettings}
        eval echo \${$var}
    )
}

old_val() {
    local var=$1
    (
        load_settings ${tmpsettings}
        eval echo \${$var}
    )
}

has_file_changed() {
    local targetfile=$1

    if [[ ! -e ${tmpsettings} ]]; then
        # first-time initialization, file changed
        return 0
    fi
    
    if [[ ! -e ${targetfile} ]]; then
        # file does not exist
        return 0
    fi

    if diff -q \
        <(load_settings ${tmpsettings}; envsubst < ${targetfile}) \
        <(load_settings ${cursettings}; envsubst < ${targetfile}) > /dev/null
    then
        # file unchanged
        return 1
    else
        # file changed
        return 0
    fi
}

have_files_changed() {
    for f in $@; do
        has_file_changed $f && return 0
    done
    return 1
}

write_file() {
    local src_file=$1 tgt_path=$2
    if [[ -d $tgt_path ]]; then
        tgt_path=$tgt_path/$(basename $src_file)
    fi

    echo "writing new version of $tgt_path"
    (
        load_settings ${cursettings}
        envsubst < $src_file > $tgt_path
    )
}

update_settings() {
    local newsettings=$(operoscfg -a)

    if [[ -e ${cursettings} ]]; then
        if diff -q ${cursettings} <(echo "${newsettings}") > /dev/null; then
            echo "settings unchanged"
            return
        fi

        echo "settings changed, updating"
        cp ${cursettings} ${tmpsettings}
    fi

    echo "${newsettings}" > ${cursettings}
}

update_password() {
    local pass=$(operoscfg -g rootpass)
    if ! grep -q "^root:${pass}:" /etc/shadow; then
        echo "setting root password"
        echo "root:${pass}" | chpasswd -e
    fi
}

update_settings
update_password
