#!/bin/bash -e
# Copyright 2018 Pax Automa Systems, Inc.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#    http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This script bootstraps the configuration that needs to be in place before
# Teamster can be launched for the first time.

set -a; . /etc/paxautoma/initial-settings; set +a

templatedir=/usr/share/operos/conf

write_file() {
    local src_file=$1 tgt_path=$2
    if [[ -d $tgt_path ]]; then
        tgt_path=$tgt_path/$(basename $src_file)
    fi

    echo "writing new version of $tgt_path"
    envsubst < $src_file > $tgt_path
}

configure_network() {
    local pub_templ=network/10-public-dhcp.network
    if [[ "${CONTROLLER_PUBLIC_IF_MODE}" != "dhcp" ]]; then
        pub_templ=network/10-public-static.network
    fi

    write_file $templatedir/$pub_templ /etc/systemd/network/10-public.network
    write_file $templatedir/network/20-private.network /etc/systemd/network/20-private.network
}

configure_network
systemctl disable bootstrap-settings.service
