#!/bin/bash -x
# Copyright 2018 Pax Automa Systems, Inc.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#    http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

wait_for_api() {
    while true; do
        /usr/bin/curl http://127.0.0.1:8080/version >/dev/null 2>&1
        result=$?
        if [ $result -eq 0 ]; then
            break
        fi
        sleep 1
    done
    sleep 3
}

MANIFEST_PATH=${MANIFEST_PATH:-/var/operos/addons}

wait_for_api
set -e

if ! ls -A ${MANIFEST_PATH}/*.yml > /dev/null 2>&1; then
    # nothing to apply
    exit 0
fi

for manifest in ${MANIFEST_PATH}/*.yml; do
    kubectl apply -f $manifest
    rm $manifest
done
