apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: default
  namespace: default
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: ceph.com/rbd
parameters:
  monitors: ${OPEROS_CONTROLLER_IP}:6789
  adminId: admin
  adminSecretName: ceph-admin-key
  adminSecretNamespace: kube-system
  pool: kube
  userId: kube
  userSecretName: ceph-secret-kube
  imageFormat: "2"
  imageFeatures: layering
